spring:
  datasource:
    name: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.19.34.7:3306/dms?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: dms
    password: albuso2o

mybatis:
  mapper-locations: classpath*:**/Mapper/*Mapper.xml
  type-aliases-package: com.rebecca.bean.Demo
